### ISSUE TITLE
Update to containerd 1.7.0

### ISSUE THREAD

**Issue by jcpunk** [docker/containerd-packaging#318]
With containerd 1.7.0 released, can this be updated to track that?

**Comment by jseba** [comment]
Any update on the package story for 1.7? There's been 3 point releases so far for 1.7 and I don't see any packaging details for it. I'm willing to take a go at it but I don't know if this is being tracked elsewhere or if there are any blockers.

**Comment by jessehu** [comment]
Hi, is there any support from docker team please? The latest containerd version is 1.7.12: https://github.com/containerd/containerd/releases/tag/v1.7.12

**Comment by thaJeztah** [comment]
We're currently packaging containerd 1.6, which is the LTS release. We have yet to decide whether we want to update the packages to 1.7, as doing so will (due to how linux package mangers work) update the version for _all_ versions of docker-ce, and 1.7 could (technically) reach EOL before 1.6.


That said; the README in this repository shows how to build a package for the version of containerd, and the distro; https://github.com/docker/containerd-packaging#usage, so if needed, you can build packages using that.

**Comment by jessehu** [comment]
Thanks a lot @thaJeztah. I'm able to build containerd-1.7.12 rpm via `make REF=v1.7.12 quay.io/centos/centos:stream8`.

**Comment by phirestalker** [comment]
> Thanks a lot @thaJeztah. I'm able to build containerd-1.7.12 rpm via `make REF=v1.7.12 quay.io/centos/centos:stream8`. BTW how about adding the centos8 tip on https://github.com/docker/containerd-packaging/blob/master/README.md#usage which only says centos7 ?

When I use the ref of v1.7.15 and ubuntu:jammy it still build 1.6.31. How can I get a 1.7 version?

**Comment by thaJeztah** [comment]
fixed by https://github.com/docker/containerd-packaging/pull/363
